<?php

namespace ContainerZtuMgk6;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailjetServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\MailjetService' shared autowired service.
     *
     * @return \App\Service\MailjetService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MailjetService.php';

        return $container->privates['App\\Service\\MailjetService'] = new \App\Service\MailjetService($container->getEnv('MAILJET_API_KEY'), $container->getEnv('MAILJET_API_SECRET'));
    }
}
