security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Authentification par formulaire
            form_login:
                login_path: login
                check_path: login
                default_target_path: /admin

            # Déconnexion (route obligatoire pour EasyAdmin)
            logout:
                path: logout
                target: login  # Redirection vers /login après déconnexion

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login, roles: PUBLIC_ACCESS }
