<?php

namespace ContainerPnsTNwf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGalleryControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9G0Mbtk.App\Controller\GalleryController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9G0Mbtk.App\\Controller\\GalleryController::index()'] = ($container->privates['.service_locator.9G0Mbtk'] ?? $container->load('get_ServiceLocator_9G0MbtkService'))->withContext('App\\Controller\\GalleryController::index()', $container);
    }
}
