<?php

namespace ContainerPnsTNwf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailjetServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\MailjetService' shared autowired service.
     *
     * @return \App\Service\MailjetService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/MailjetService.php';

        return $container->privates['App\\Service\\MailjetService'] = new \App\Service\MailjetService($container->getEnv('MAILJET_API_KEY'), $container->getEnv('MAILJET_API_SECRET'));
    }
}
