<?php

namespace ContainerGKOOEJP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L5E0O9OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.L5E0O9O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.L5E0O9O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => ['privates', '.service_locator.5FanY8e.App\\Controller\\Admin\\DashboardController::configureUserMenu()', 'getDashboardControllerconfigureUserMenuService', true],
            'App\\Controller\\Admin\\PhotoCrudController::configureCrud' => ['privates', '.service_locator.OoSfY9L.App\\Controller\\Admin\\PhotoCrudController::configureCrud()', 'getPhotoCrudControllerconfigureCrudService', true],
            'App\\Controller\\Admin\\PhotoCrudController::configureAssets' => ['privates', '.service_locator.PE.ZUUL.App\\Controller\\Admin\\PhotoCrudController::configureAssets()', 'getPhotoCrudControllerconfigureAssetsService', true],
            'App\\Controller\\Admin\\PhotoCrudController::configureActions' => ['privates', '.service_locator.T.Ra9lS.App\\Controller\\Admin\\PhotoCrudController::configureActions()', 'getPhotoCrudControllerconfigureActionsService', true],
            'App\\Controller\\Admin\\PhotoCrudController::configureFilters' => ['privates', '.service_locator.CFbfVRp.App\\Controller\\Admin\\PhotoCrudController::configureFilters()', 'getPhotoCrudControllerconfigureFiltersService', true],
            'App\\Controller\\Admin\\PhotoCrudController::index' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::index()', 'getPhotoCrudControllerindexService', true],
            'App\\Controller\\Admin\\PhotoCrudController::detail' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::detail()', 'getPhotoCrudControllerdetailService', true],
            'App\\Controller\\Admin\\PhotoCrudController::edit' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::edit()', 'getPhotoCrudControllereditService', true],
            'App\\Controller\\Admin\\PhotoCrudController::new' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::new()', 'getPhotoCrudControllernewService', true],
            'App\\Controller\\Admin\\PhotoCrudController::delete' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::delete()', 'getPhotoCrudControllerdeleteService', true],
            'App\\Controller\\Admin\\PhotoCrudController::batchDelete' => ['privates', '.service_locator.oDo8ofG.App\\Controller\\Admin\\PhotoCrudController::batchDelete()', 'getPhotoCrudControllerbatchDeleteService', true],
            'App\\Controller\\Admin\\PhotoCrudController::autocomplete' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::autocomplete()', 'getPhotoCrudControllerautocompleteService', true],
            'App\\Controller\\Admin\\PhotoCrudController::createIndexQueryBuilder' => ['privates', '.service_locator.kqcX6wc.App\\Controller\\Admin\\PhotoCrudController::createIndexQueryBuilder()', 'getPhotoCrudControllercreateIndexQueryBuilderService', true],
            'App\\Controller\\Admin\\PhotoCrudController::renderFilters' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::renderFilters()', 'getPhotoCrudControllerrenderFiltersService', true],
            'App\\Controller\\Admin\\PhotoCrudController::updateEntity' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\PhotoCrudController::updateEntity()', 'getPhotoCrudControllerupdateEntityService', true],
            'App\\Controller\\Admin\\PhotoCrudController::persistEntity' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\PhotoCrudController::persistEntity()', 'getPhotoCrudControllerpersistEntityService', true],
            'App\\Controller\\Admin\\PhotoCrudController::deleteEntity' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\PhotoCrudController::deleteEntity()', 'getPhotoCrudControllerdeleteEntityService', true],
            'App\\Controller\\Admin\\PhotoCrudController::createEditForm' => ['privates', '.service_locator.CaejQBj.App\\Controller\\Admin\\PhotoCrudController::createEditForm()', 'getPhotoCrudControllercreateEditFormService', true],
            'App\\Controller\\Admin\\PhotoCrudController::createEditFormBuilder' => ['privates', '.service_locator.CaejQBj.App\\Controller\\Admin\\PhotoCrudController::createEditFormBuilder()', 'getPhotoCrudControllercreateEditFormBuilderService', true],
            'App\\Controller\\Admin\\PhotoCrudController::createNewForm' => ['privates', '.service_locator.CaejQBj.App\\Controller\\Admin\\PhotoCrudController::createNewForm()', 'getPhotoCrudControllercreateNewFormService', true],
            'App\\Controller\\Admin\\PhotoCrudController::createNewFormBuilder' => ['privates', '.service_locator.CaejQBj.App\\Controller\\Admin\\PhotoCrudController::createNewFormBuilder()', 'getPhotoCrudControllercreateNewFormBuilderService', true],
            'App\\Controller\\Admin\\PhotoCrudController::configureResponseParameters' => ['privates', '.service_locator.ib1WIGE.App\\Controller\\Admin\\PhotoCrudController::configureResponseParameters()', 'getPhotoCrudControllerconfigureResponseParametersService', true],
            'App\\Controller\\AppointmentController::form' => ['privates', '.service_locator.7q9j4Qi.App\\Controller\\AppointmentController::form()', 'getAppointmentControllerformService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => ['privates', '.service_locator.5FanY8e.App\\Controller\\Admin\\DashboardController::configureUserMenu()', 'getDashboardControllerconfigureUserMenuService', true],
            'App\\Controller\\Admin\\PhotoCrudController:configureCrud' => ['privates', '.service_locator.OoSfY9L.App\\Controller\\Admin\\PhotoCrudController::configureCrud()', 'getPhotoCrudControllerconfigureCrudService', true],
            'App\\Controller\\Admin\\PhotoCrudController:configureAssets' => ['privates', '.service_locator.PE.ZUUL.App\\Controller\\Admin\\PhotoCrudController::configureAssets()', 'getPhotoCrudControllerconfigureAssetsService', true],
            'App\\Controller\\Admin\\PhotoCrudController:configureActions' => ['privates', '.service_locator.T.Ra9lS.App\\Controller\\Admin\\PhotoCrudController::configureActions()', 'getPhotoCrudControllerconfigureActionsService', true],
            'App\\Controller\\Admin\\PhotoCrudController:configureFilters' => ['privates', '.service_locator.CFbfVRp.App\\Controller\\Admin\\PhotoCrudController::configureFilters()', 'getPhotoCrudControllerconfigureFiltersService', true],
            'App\\Controller\\Admin\\PhotoCrudController:index' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::index()', 'getPhotoCrudControllerindexService', true],
            'App\\Controller\\Admin\\PhotoCrudController:detail' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::detail()', 'getPhotoCrudControllerdetailService', true],
            'App\\Controller\\Admin\\PhotoCrudController:edit' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::edit()', 'getPhotoCrudControllereditService', true],
            'App\\Controller\\Admin\\PhotoCrudController:new' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::new()', 'getPhotoCrudControllernewService', true],
            'App\\Controller\\Admin\\PhotoCrudController:delete' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::delete()', 'getPhotoCrudControllerdeleteService', true],
            'App\\Controller\\Admin\\PhotoCrudController:batchDelete' => ['privates', '.service_locator.oDo8ofG.App\\Controller\\Admin\\PhotoCrudController::batchDelete()', 'getPhotoCrudControllerbatchDeleteService', true],
            'App\\Controller\\Admin\\PhotoCrudController:autocomplete' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::autocomplete()', 'getPhotoCrudControllerautocompleteService', true],
            'App\\Controller\\Admin\\PhotoCrudController:createIndexQueryBuilder' => ['privates', '.service_locator.kqcX6wc.App\\Controller\\Admin\\PhotoCrudController::createIndexQueryBuilder()', 'getPhotoCrudControllercreateIndexQueryBuilderService', true],
            'App\\Controller\\Admin\\PhotoCrudController:renderFilters' => ['privates', '.service_locator.IaSFwjD.App\\Controller\\Admin\\PhotoCrudController::renderFilters()', 'getPhotoCrudControllerrenderFiltersService', true],
            'App\\Controller\\Admin\\PhotoCrudController:updateEntity' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\PhotoCrudController::updateEntity()', 'getPhotoCrudControllerupdateEntityService', true],
            'App\\Controller\\Admin\\PhotoCrudController:persistEntity' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\PhotoCrudController::persistEntity()', 'getPhotoCrudControllerpersistEntityService', true],
            'App\\Controller\\Admin\\PhotoCrudController:deleteEntity' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\PhotoCrudController::deleteEntity()', 'getPhotoCrudControllerdeleteEntityService', true],
            'App\\Controller\\Admin\\PhotoCrudController:createEditForm' => ['privates', '.service_locator.CaejQBj.App\\Controller\\Admin\\PhotoCrudController::createEditForm()', 'getPhotoCrudControllercreateEditFormService', true],
            'App\\Controller\\Admin\\PhotoCrudController:createEditFormBuilder' => ['privates', '.service_locator.CaejQBj.App\\Controller\\Admin\\PhotoCrudController::createEditFormBuilder()', 'getPhotoCrudControllercreateEditFormBuilderService', true],
            'App\\Controller\\Admin\\PhotoCrudController:createNewForm' => ['privates', '.service_locator.CaejQBj.App\\Controller\\Admin\\PhotoCrudController::createNewForm()', 'getPhotoCrudControllercreateNewFormService', true],
            'App\\Controller\\Admin\\PhotoCrudController:createNewFormBuilder' => ['privates', '.service_locator.CaejQBj.App\\Controller\\Admin\\PhotoCrudController::createNewFormBuilder()', 'getPhotoCrudControllercreateNewFormBuilderService', true],
            'App\\Controller\\Admin\\PhotoCrudController:configureResponseParameters' => ['privates', '.service_locator.ib1WIGE.App\\Controller\\Admin\\PhotoCrudController::configureResponseParameters()', 'getPhotoCrudControllerconfigureResponseParametersService', true],
            'App\\Controller\\AppointmentController:form' => ['privates', '.service_locator.7q9j4Qi.App\\Controller\\AppointmentController::form()', 'getAppointmentControllerformService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::configureCrud' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::configureAssets' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::configureActions' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::configureFilters' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::index' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::detail' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::edit' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::new' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::delete' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::batchDelete' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::autocomplete' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::createIndexQueryBuilder' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::renderFilters' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::updateEntity' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::persistEntity' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::deleteEntity' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::createEditForm' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::createEditFormBuilder' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::createNewForm' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::createNewFormBuilder' => '?',
            'App\\Controller\\Admin\\PhotoCrudController::configureResponseParameters' => '?',
            'App\\Controller\\AppointmentController::form' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:configureCrud' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:configureAssets' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:configureActions' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:configureFilters' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:index' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:detail' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:edit' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:new' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:delete' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:batchDelete' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:autocomplete' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:createIndexQueryBuilder' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:renderFilters' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:updateEntity' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:persistEntity' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:deleteEntity' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:createEditForm' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:createEditFormBuilder' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:createNewForm' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:createNewFormBuilder' => '?',
            'App\\Controller\\Admin\\PhotoCrudController:configureResponseParameters' => '?',
            'App\\Controller\\AppointmentController:form' => '?',
        ]);
    }
}
