<?php

namespace ContainerDTahfMC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppointmentControllerformService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7q9j4Qi.App\Controller\AppointmentController::form()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7q9j4Qi.App\\Controller\\AppointmentController::form()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailjet' => ['privates', 'App\\Service\\MailjetService', 'getMailjetServiceService', true],
        ], [
            'mailjet' => 'App\\Service\\MailjetService',
        ]))->withContext('App\\Controller\\AppointmentController::form()', $container);
    }
}
