<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO4KTHuu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO4KTHuu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO4KTHuu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO4KTHuu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO4KTHuu\App_KernelDevDebugContainer([
    'container.build_hash' => 'O4KTHuu',
    'container.build_id' => '26947f14',
    'container.build_time' => 1747983594,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO4KTHuu');
