<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIoTQYT6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIoTQYT6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIoTQYT6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIoTQYT6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIoTQYT6\App_KernelDevDebugContainer([
    'container.build_hash' => 'IoTQYT6',
    'container.build_id' => '0a4ff405',
    'container.build_time' => 1749642584,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIoTQYT6');
