<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJGPTQ6g\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJGPTQ6g/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJGPTQ6g.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJGPTQ6g\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJGPTQ6g\App_KernelDevDebugContainer([
    'container.build_hash' => 'JGPTQ6g',
    'container.build_id' => '25b4a945',
    'container.build_time' => 1747921095,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJGPTQ6g');
